### ISSUE TITLE
can't install the package

### ISSUE THREAD

**Issue by ciwaya** [psolymos/EDMAinR#10]
Hello,

I can't install the package.
my R version is 2023.06.0+421 (2023.06.0+421)

I typed
if (!require(EDMAinR)) {
  if (!require(remotes))
    install.packages("remotes")
  remotes::install_github("psolymos/EDMAinR")
}
1
yes 

Then
library(EDMAinR)

Error message is here
Error in library(EDMAinR) : there is no package called ‘EDMAinR’

Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE,  ... :
  there is no package called ‘EDMAinR’
2: In i.p(...) : installation of package ‘tinytex’ had non-zero exit status
3: In i.p(...) : installation of package ‘bslib’ had non-zero exit status
4: In i.p(...) : installation of package ‘shapes’ had non-zero exit status
5: In i.p(...) : installation of package ‘rmarkdown’ had non-zero exit status
6: In i.p(...) : installation of package ‘htmlwidgets’ had non-zero exit status

could you help me to solve this isuue?

**Comment by psolymos** [comment]
Please try installing this way:

```R
install.packages('EDMAinR', repos = c('https://psolymos.r-universe.dev', 'https://cloud.r-project.org'), dependencies = TRUE)
```

**Comment by ciwaya** [comment]
Thank you for your reply.
I got same error message.

install.packages('EDMAinR', 
                 repos = c('https://psolymos.r-universe.dev', 'https://cloud.r-project.org'), 
                 dependencies = TRUE)

> library(EDMAinR)
Error in library(EDMAinR) : there is no package called ‘EDMAinR’

**Comment by psolymos** [comment]
- What system are you on? Win/Mac/Linux?
- Can you identify which package install fails? I.e. tinytex etc? I think the package doesn't get installed because one of the dependencies are missing.

**Comment by ciwaya** [comment]
I am using Mac.

I copied the warning message here.
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘htmltools’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/htmltools’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/htmltools’
Warning in install.packages :
  installation of package ‘htmltools’ had non-zero exit status
* installing *source* package ‘minpack.lm’ ...
** package ‘minpack.lm’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘minpack.lm’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/minpack.lm’
Warning in install.packages :
  installation of package ‘minpack.lm’ had non-zero exit status
* installing *source* package ‘xfun’ ...
** package ‘xfun’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘xfun’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/xfun’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/xfun’
Warning in install.packages :
  installation of package ‘xfun’ had non-zero exit status
* installing *source* package ‘ape’ ...
** package ‘ape’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘ape’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ape’
Warning in install.packages :
  installation of package ‘ape’ had non-zero exit status
* installing *source* package ‘sass’ ...
** package ‘sass’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘sass’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/sass’
Warning in install.packages :
  installation of package ‘sass’ had non-zero exit status
* installing *source* package ‘tinytex’ ...
** package ‘tinytex’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘xfun’ 0.22 is being loaded, but >= 0.29 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
ERROR: lazy loading failed for package ‘tinytex’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/tinytex’
Warning in install.packages :
  installation of package ‘tinytex’ had non-zero exit status
ERROR: dependency ‘sass’ is not available for package ‘bslib’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/bslib’
Warning in install.packages :
  installation of package ‘bslib’ had non-zero exit status
ERROR: dependencies ‘bslib’, ‘tinytex’ are not available for package ‘rmarkdown’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rmarkdown’
Warning in install.packages :
  installation of package ‘rmarkdown’ had non-zero exit status
ERROR: dependency ‘rmarkdown’ is not available for package ‘htmlwidgets’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/htmlwidgets’
Warning in install.packages :
  installation of package ‘htmlwidgets’ had non-zero exit status
ERROR: dependency ‘htmlwidgets’ is not available for package ‘rgl’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rgl’
Warning in install.packages :
  installation of package ‘rgl’ had non-zero exit status
ERROR: dependency ‘htmlwidgets’ is not available for package ‘plotly’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/plotly’
Warning in install.packages :
  installation of package ‘plotly’ had non-zero exit status
ERROR: dependencies ‘minpack.lm’, ‘rgl’ are not available for package ‘shapes’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/shapes’
Warning in install.packages :
  installation of package ‘shapes’ had non-zero exit status
ERROR: dependencies ‘ape’, ‘shapes’ are not available for package ‘EDMAinR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/EDMAinR’
Warning in install.packages :
  installation of package ‘EDMAinR’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/1s/8skwndz17z344nr42cngt37r0000gn/T/RtmpOvPpEe/downloaded_packages’

**Comment by psolymos** [comment]
Have you installed xcode? See https://community.rstudio.com/t/xcrun-error-invalid-active-developer-path-library-developer-commandlinetools-missing-xcrun-at-library-developer-commandlinetools-usr-bin-xcrun-error-compilation-failed-for-package-rlang/27553/4

**Comment by ciwaya** [comment]
I did.

Still showing warning.

Warning in install.packages :
  unable to access index for repository https://cloud.r-project.org/bin/macosx/el-capitan/contrib/3.6:
  cannot open URL 'https://cloud.r-project.org/bin/macosx/el-capitan/contrib/3.6/PACKAGES'
Packages which are only available in source form, and may need
  compilation of C/C++/Fortran: ‘htmltools’ ‘sass’ ‘minpack.lm’
  ‘xfun’ ‘ape’ ‘rgl’

**Comment by psolymos** [comment]
Looks like you are using R version 3.6 which is now almost 3 years old. You might want to consider upgrading R to 4.3. The warning tells you the R version for which the package index is not available (which is odd). You can also just replace the cloud.r-project.org from the repos argument with a different CRAN mirror.

**Comment by psolymos** [comment]
Were you able to load EDMAinR?

The warning says that there are no binary versions of those packages but those might have been installed from source.

**Comment by ciwaya** [comment]
Hello,
I used Latest version of R studio

RStudio 2023.06.0+421 "Mountain Hydrangea" Release (583b465ecc45e60ee9de085148cd2f9741cc5214, 2023-06-05) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.06.0+421 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36

Should I use R not R studio?
I can't install.

**Comment by psolymos** [comment]
Your R version is independent of RStudio, and RStudio is an IDE for R not R itself. Install R from r-project.org

**Comment by ciwaya** [comment]
Thank you very much for all your help!
I installed!

**Comment by psolymos** [comment]
You are welcome.
